# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "D:\CLion 2018.3.3\bin\cmake\win\bin\cmake.exe"

# The command to remove a file.
RM = "D:\CLion 2018.3.3\bin\cmake\win\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "F:\SJTU\Semester 1\Programming\OOP2-Basic"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "F:\SJTU\Semester 1\Programming\OOP2-Basic\cmake-build-debug"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	"D:\CLion 2018.3.3\bin\cmake\win\bin\cmake.exe" -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"D:\CLion 2018.3.3\bin\cmake\win\bin\cmake.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "F:\SJTU\Semester 1\Programming\OOP2-Basic\cmake-build-debug\CMakeFiles" "F:\SJTU\Semester 1\Programming\OOP2-Basic\cmake-build-debug\CMakeFiles\progress.marks"
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "F:\SJTU\Semester 1\Programming\OOP2-Basic\cmake-build-debug\CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named basic_program

# Build rule for target.
basic_program: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 basic_program
.PHONY : basic_program

# fast build rule for target.
basic_program/fast:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/build
.PHONY : basic_program/fast

Basic/Basic.obj: Basic/Basic.cpp.obj

.PHONY : Basic/Basic.obj

# target to build an object file
Basic/Basic.cpp.obj:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/Basic/Basic.cpp.obj
.PHONY : Basic/Basic.cpp.obj

Basic/Basic.i: Basic/Basic.cpp.i

.PHONY : Basic/Basic.i

# target to preprocess a source file
Basic/Basic.cpp.i:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/Basic/Basic.cpp.i
.PHONY : Basic/Basic.cpp.i

Basic/Basic.s: Basic/Basic.cpp.s

.PHONY : Basic/Basic.s

# target to generate assembly for a file
Basic/Basic.cpp.s:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/Basic/Basic.cpp.s
.PHONY : Basic/Basic.cpp.s

Basic/evalstate.obj: Basic/evalstate.cpp.obj

.PHONY : Basic/evalstate.obj

# target to build an object file
Basic/evalstate.cpp.obj:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/Basic/evalstate.cpp.obj
.PHONY : Basic/evalstate.cpp.obj

Basic/evalstate.i: Basic/evalstate.cpp.i

.PHONY : Basic/evalstate.i

# target to preprocess a source file
Basic/evalstate.cpp.i:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/Basic/evalstate.cpp.i
.PHONY : Basic/evalstate.cpp.i

Basic/evalstate.s: Basic/evalstate.cpp.s

.PHONY : Basic/evalstate.s

# target to generate assembly for a file
Basic/evalstate.cpp.s:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/Basic/evalstate.cpp.s
.PHONY : Basic/evalstate.cpp.s

Basic/exp.obj: Basic/exp.cpp.obj

.PHONY : Basic/exp.obj

# target to build an object file
Basic/exp.cpp.obj:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/Basic/exp.cpp.obj
.PHONY : Basic/exp.cpp.obj

Basic/exp.i: Basic/exp.cpp.i

.PHONY : Basic/exp.i

# target to preprocess a source file
Basic/exp.cpp.i:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/Basic/exp.cpp.i
.PHONY : Basic/exp.cpp.i

Basic/exp.s: Basic/exp.cpp.s

.PHONY : Basic/exp.s

# target to generate assembly for a file
Basic/exp.cpp.s:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/Basic/exp.cpp.s
.PHONY : Basic/exp.cpp.s

Basic/parser.obj: Basic/parser.cpp.obj

.PHONY : Basic/parser.obj

# target to build an object file
Basic/parser.cpp.obj:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/Basic/parser.cpp.obj
.PHONY : Basic/parser.cpp.obj

Basic/parser.i: Basic/parser.cpp.i

.PHONY : Basic/parser.i

# target to preprocess a source file
Basic/parser.cpp.i:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/Basic/parser.cpp.i
.PHONY : Basic/parser.cpp.i

Basic/parser.s: Basic/parser.cpp.s

.PHONY : Basic/parser.s

# target to generate assembly for a file
Basic/parser.cpp.s:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/Basic/parser.cpp.s
.PHONY : Basic/parser.cpp.s

Basic/program.obj: Basic/program.cpp.obj

.PHONY : Basic/program.obj

# target to build an object file
Basic/program.cpp.obj:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/Basic/program.cpp.obj
.PHONY : Basic/program.cpp.obj

Basic/program.i: Basic/program.cpp.i

.PHONY : Basic/program.i

# target to preprocess a source file
Basic/program.cpp.i:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/Basic/program.cpp.i
.PHONY : Basic/program.cpp.i

Basic/program.s: Basic/program.cpp.s

.PHONY : Basic/program.s

# target to generate assembly for a file
Basic/program.cpp.s:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/Basic/program.cpp.s
.PHONY : Basic/program.cpp.s

Basic/statement.obj: Basic/statement.cpp.obj

.PHONY : Basic/statement.obj

# target to build an object file
Basic/statement.cpp.obj:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/Basic/statement.cpp.obj
.PHONY : Basic/statement.cpp.obj

Basic/statement.i: Basic/statement.cpp.i

.PHONY : Basic/statement.i

# target to preprocess a source file
Basic/statement.cpp.i:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/Basic/statement.cpp.i
.PHONY : Basic/statement.cpp.i

Basic/statement.s: Basic/statement.cpp.s

.PHONY : Basic/statement.s

# target to generate assembly for a file
Basic/statement.cpp.s:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/Basic/statement.cpp.s
.PHONY : Basic/statement.cpp.s

StanfordCPPLib/direction.obj: StanfordCPPLib/direction.cpp.obj

.PHONY : StanfordCPPLib/direction.obj

# target to build an object file
StanfordCPPLib/direction.cpp.obj:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/StanfordCPPLib/direction.cpp.obj
.PHONY : StanfordCPPLib/direction.cpp.obj

StanfordCPPLib/direction.i: StanfordCPPLib/direction.cpp.i

.PHONY : StanfordCPPLib/direction.i

# target to preprocess a source file
StanfordCPPLib/direction.cpp.i:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/StanfordCPPLib/direction.cpp.i
.PHONY : StanfordCPPLib/direction.cpp.i

StanfordCPPLib/direction.s: StanfordCPPLib/direction.cpp.s

.PHONY : StanfordCPPLib/direction.s

# target to generate assembly for a file
StanfordCPPLib/direction.cpp.s:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/StanfordCPPLib/direction.cpp.s
.PHONY : StanfordCPPLib/direction.cpp.s

StanfordCPPLib/error.obj: StanfordCPPLib/error.cpp.obj

.PHONY : StanfordCPPLib/error.obj

# target to build an object file
StanfordCPPLib/error.cpp.obj:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/StanfordCPPLib/error.cpp.obj
.PHONY : StanfordCPPLib/error.cpp.obj

StanfordCPPLib/error.i: StanfordCPPLib/error.cpp.i

.PHONY : StanfordCPPLib/error.i

# target to preprocess a source file
StanfordCPPLib/error.cpp.i:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/StanfordCPPLib/error.cpp.i
.PHONY : StanfordCPPLib/error.cpp.i

StanfordCPPLib/error.s: StanfordCPPLib/error.cpp.s

.PHONY : StanfordCPPLib/error.s

# target to generate assembly for a file
StanfordCPPLib/error.cpp.s:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/StanfordCPPLib/error.cpp.s
.PHONY : StanfordCPPLib/error.cpp.s

StanfordCPPLib/gmath.obj: StanfordCPPLib/gmath.cpp.obj

.PHONY : StanfordCPPLib/gmath.obj

# target to build an object file
StanfordCPPLib/gmath.cpp.obj:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/StanfordCPPLib/gmath.cpp.obj
.PHONY : StanfordCPPLib/gmath.cpp.obj

StanfordCPPLib/gmath.i: StanfordCPPLib/gmath.cpp.i

.PHONY : StanfordCPPLib/gmath.i

# target to preprocess a source file
StanfordCPPLib/gmath.cpp.i:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/StanfordCPPLib/gmath.cpp.i
.PHONY : StanfordCPPLib/gmath.cpp.i

StanfordCPPLib/gmath.s: StanfordCPPLib/gmath.cpp.s

.PHONY : StanfordCPPLib/gmath.s

# target to generate assembly for a file
StanfordCPPLib/gmath.cpp.s:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/StanfordCPPLib/gmath.cpp.s
.PHONY : StanfordCPPLib/gmath.cpp.s

StanfordCPPLib/gtypes.obj: StanfordCPPLib/gtypes.cpp.obj

.PHONY : StanfordCPPLib/gtypes.obj

# target to build an object file
StanfordCPPLib/gtypes.cpp.obj:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/StanfordCPPLib/gtypes.cpp.obj
.PHONY : StanfordCPPLib/gtypes.cpp.obj

StanfordCPPLib/gtypes.i: StanfordCPPLib/gtypes.cpp.i

.PHONY : StanfordCPPLib/gtypes.i

# target to preprocess a source file
StanfordCPPLib/gtypes.cpp.i:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/StanfordCPPLib/gtypes.cpp.i
.PHONY : StanfordCPPLib/gtypes.cpp.i

StanfordCPPLib/gtypes.s: StanfordCPPLib/gtypes.cpp.s

.PHONY : StanfordCPPLib/gtypes.s

# target to generate assembly for a file
StanfordCPPLib/gtypes.cpp.s:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/StanfordCPPLib/gtypes.cpp.s
.PHONY : StanfordCPPLib/gtypes.cpp.s

StanfordCPPLib/hashmap.obj: StanfordCPPLib/hashmap.cpp.obj

.PHONY : StanfordCPPLib/hashmap.obj

# target to build an object file
StanfordCPPLib/hashmap.cpp.obj:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/StanfordCPPLib/hashmap.cpp.obj
.PHONY : StanfordCPPLib/hashmap.cpp.obj

StanfordCPPLib/hashmap.i: StanfordCPPLib/hashmap.cpp.i

.PHONY : StanfordCPPLib/hashmap.i

# target to preprocess a source file
StanfordCPPLib/hashmap.cpp.i:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/StanfordCPPLib/hashmap.cpp.i
.PHONY : StanfordCPPLib/hashmap.cpp.i

StanfordCPPLib/hashmap.s: StanfordCPPLib/hashmap.cpp.s

.PHONY : StanfordCPPLib/hashmap.s

# target to generate assembly for a file
StanfordCPPLib/hashmap.cpp.s:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/StanfordCPPLib/hashmap.cpp.s
.PHONY : StanfordCPPLib/hashmap.cpp.s

StanfordCPPLib/lexicon.obj: StanfordCPPLib/lexicon.cpp.obj

.PHONY : StanfordCPPLib/lexicon.obj

# target to build an object file
StanfordCPPLib/lexicon.cpp.obj:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/StanfordCPPLib/lexicon.cpp.obj
.PHONY : StanfordCPPLib/lexicon.cpp.obj

StanfordCPPLib/lexicon.i: StanfordCPPLib/lexicon.cpp.i

.PHONY : StanfordCPPLib/lexicon.i

# target to preprocess a source file
StanfordCPPLib/lexicon.cpp.i:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/StanfordCPPLib/lexicon.cpp.i
.PHONY : StanfordCPPLib/lexicon.cpp.i

StanfordCPPLib/lexicon.s: StanfordCPPLib/lexicon.cpp.s

.PHONY : StanfordCPPLib/lexicon.s

# target to generate assembly for a file
StanfordCPPLib/lexicon.cpp.s:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/StanfordCPPLib/lexicon.cpp.s
.PHONY : StanfordCPPLib/lexicon.cpp.s

StanfordCPPLib/point.obj: StanfordCPPLib/point.cpp.obj

.PHONY : StanfordCPPLib/point.obj

# target to build an object file
StanfordCPPLib/point.cpp.obj:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/StanfordCPPLib/point.cpp.obj
.PHONY : StanfordCPPLib/point.cpp.obj

StanfordCPPLib/point.i: StanfordCPPLib/point.cpp.i

.PHONY : StanfordCPPLib/point.i

# target to preprocess a source file
StanfordCPPLib/point.cpp.i:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/StanfordCPPLib/point.cpp.i
.PHONY : StanfordCPPLib/point.cpp.i

StanfordCPPLib/point.s: StanfordCPPLib/point.cpp.s

.PHONY : StanfordCPPLib/point.s

# target to generate assembly for a file
StanfordCPPLib/point.cpp.s:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/StanfordCPPLib/point.cpp.s
.PHONY : StanfordCPPLib/point.cpp.s

StanfordCPPLib/random.obj: StanfordCPPLib/random.cpp.obj

.PHONY : StanfordCPPLib/random.obj

# target to build an object file
StanfordCPPLib/random.cpp.obj:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/StanfordCPPLib/random.cpp.obj
.PHONY : StanfordCPPLib/random.cpp.obj

StanfordCPPLib/random.i: StanfordCPPLib/random.cpp.i

.PHONY : StanfordCPPLib/random.i

# target to preprocess a source file
StanfordCPPLib/random.cpp.i:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/StanfordCPPLib/random.cpp.i
.PHONY : StanfordCPPLib/random.cpp.i

StanfordCPPLib/random.s: StanfordCPPLib/random.cpp.s

.PHONY : StanfordCPPLib/random.s

# target to generate assembly for a file
StanfordCPPLib/random.cpp.s:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/StanfordCPPLib/random.cpp.s
.PHONY : StanfordCPPLib/random.cpp.s

StanfordCPPLib/simpio.obj: StanfordCPPLib/simpio.cpp.obj

.PHONY : StanfordCPPLib/simpio.obj

# target to build an object file
StanfordCPPLib/simpio.cpp.obj:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/StanfordCPPLib/simpio.cpp.obj
.PHONY : StanfordCPPLib/simpio.cpp.obj

StanfordCPPLib/simpio.i: StanfordCPPLib/simpio.cpp.i

.PHONY : StanfordCPPLib/simpio.i

# target to preprocess a source file
StanfordCPPLib/simpio.cpp.i:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/StanfordCPPLib/simpio.cpp.i
.PHONY : StanfordCPPLib/simpio.cpp.i

StanfordCPPLib/simpio.s: StanfordCPPLib/simpio.cpp.s

.PHONY : StanfordCPPLib/simpio.s

# target to generate assembly for a file
StanfordCPPLib/simpio.cpp.s:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/StanfordCPPLib/simpio.cpp.s
.PHONY : StanfordCPPLib/simpio.cpp.s

StanfordCPPLib/strlib.obj: StanfordCPPLib/strlib.cpp.obj

.PHONY : StanfordCPPLib/strlib.obj

# target to build an object file
StanfordCPPLib/strlib.cpp.obj:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/StanfordCPPLib/strlib.cpp.obj
.PHONY : StanfordCPPLib/strlib.cpp.obj

StanfordCPPLib/strlib.i: StanfordCPPLib/strlib.cpp.i

.PHONY : StanfordCPPLib/strlib.i

# target to preprocess a source file
StanfordCPPLib/strlib.cpp.i:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/StanfordCPPLib/strlib.cpp.i
.PHONY : StanfordCPPLib/strlib.cpp.i

StanfordCPPLib/strlib.s: StanfordCPPLib/strlib.cpp.s

.PHONY : StanfordCPPLib/strlib.s

# target to generate assembly for a file
StanfordCPPLib/strlib.cpp.s:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/StanfordCPPLib/strlib.cpp.s
.PHONY : StanfordCPPLib/strlib.cpp.s

StanfordCPPLib/tokenscanner.obj: StanfordCPPLib/tokenscanner.cpp.obj

.PHONY : StanfordCPPLib/tokenscanner.obj

# target to build an object file
StanfordCPPLib/tokenscanner.cpp.obj:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/StanfordCPPLib/tokenscanner.cpp.obj
.PHONY : StanfordCPPLib/tokenscanner.cpp.obj

StanfordCPPLib/tokenscanner.i: StanfordCPPLib/tokenscanner.cpp.i

.PHONY : StanfordCPPLib/tokenscanner.i

# target to preprocess a source file
StanfordCPPLib/tokenscanner.cpp.i:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/StanfordCPPLib/tokenscanner.cpp.i
.PHONY : StanfordCPPLib/tokenscanner.cpp.i

StanfordCPPLib/tokenscanner.s: StanfordCPPLib/tokenscanner.cpp.s

.PHONY : StanfordCPPLib/tokenscanner.s

# target to generate assembly for a file
StanfordCPPLib/tokenscanner.cpp.s:
	$(MAKE) -f CMakeFiles\basic_program.dir\build.make CMakeFiles/basic_program.dir/StanfordCPPLib/tokenscanner.cpp.s
.PHONY : StanfordCPPLib/tokenscanner.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... basic_program
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... Basic/Basic.obj
	@echo ... Basic/Basic.i
	@echo ... Basic/Basic.s
	@echo ... Basic/evalstate.obj
	@echo ... Basic/evalstate.i
	@echo ... Basic/evalstate.s
	@echo ... Basic/exp.obj
	@echo ... Basic/exp.i
	@echo ... Basic/exp.s
	@echo ... Basic/parser.obj
	@echo ... Basic/parser.i
	@echo ... Basic/parser.s
	@echo ... Basic/program.obj
	@echo ... Basic/program.i
	@echo ... Basic/program.s
	@echo ... Basic/statement.obj
	@echo ... Basic/statement.i
	@echo ... Basic/statement.s
	@echo ... StanfordCPPLib/direction.obj
	@echo ... StanfordCPPLib/direction.i
	@echo ... StanfordCPPLib/direction.s
	@echo ... StanfordCPPLib/error.obj
	@echo ... StanfordCPPLib/error.i
	@echo ... StanfordCPPLib/error.s
	@echo ... StanfordCPPLib/gmath.obj
	@echo ... StanfordCPPLib/gmath.i
	@echo ... StanfordCPPLib/gmath.s
	@echo ... StanfordCPPLib/gtypes.obj
	@echo ... StanfordCPPLib/gtypes.i
	@echo ... StanfordCPPLib/gtypes.s
	@echo ... StanfordCPPLib/hashmap.obj
	@echo ... StanfordCPPLib/hashmap.i
	@echo ... StanfordCPPLib/hashmap.s
	@echo ... StanfordCPPLib/lexicon.obj
	@echo ... StanfordCPPLib/lexicon.i
	@echo ... StanfordCPPLib/lexicon.s
	@echo ... StanfordCPPLib/point.obj
	@echo ... StanfordCPPLib/point.i
	@echo ... StanfordCPPLib/point.s
	@echo ... StanfordCPPLib/random.obj
	@echo ... StanfordCPPLib/random.i
	@echo ... StanfordCPPLib/random.s
	@echo ... StanfordCPPLib/simpio.obj
	@echo ... StanfordCPPLib/simpio.i
	@echo ... StanfordCPPLib/simpio.s
	@echo ... StanfordCPPLib/strlib.obj
	@echo ... StanfordCPPLib/strlib.i
	@echo ... StanfordCPPLib/strlib.s
	@echo ... StanfordCPPLib/tokenscanner.obj
	@echo ... StanfordCPPLib/tokenscanner.i
	@echo ... StanfordCPPLib/tokenscanner.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

